require('dotenv').config();
const path=require('path'); const express=require('express'); const session=require('express-session'); const pgSession=require('connect-pg-simple')(session); const {Pool}=require('pg'); const bcrypt=require('bcryptjs');
const app=express(), PORT=process.env.PORT||3000;
if(!process.env.DATABASE_URL||!process.env.SESSION_SECRET){console.error('Set DATABASE_URL and SESSION_SECRET');process.exit(1)}
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});
app.set('trust proxy',1); app.use(express.json()); app.use(express.urlencoded({extended:true}));
app.use(session({store:new pgSession({pool,tableName:'user_sessions',createTableIfMissing:true}),secret:process.env.SESSION_SECRET,resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:8*60*60*1000}}));
app.use(express.static(path.join(__dirname,'public')));
const categories=['Infrastructure','Hostel','Academics','Transport','Food & Canteen','Safety','IT & Wi-Fi','Other']; const severities=['low','medium','high','critical']; const statuses=['open','in_review','resolved'];
const userOut=u=>({id:u.id,name:u.name,email:u.email,role:u.role}); const choice=(v,a)=>typeof v==='string'&&a.includes(v);
const auth=(req,res,next)=>req.session.user?next():res.status(401).json({error:'Please log in.'}); const role=r=>(req,res,next)=>req.session.user?.role===r?next():res.status(403).json({error:'Permission denied.'});
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(255) UNIQUE NOT NULL,password_hash TEXT NOT NULL,role VARCHAR(20) NOT NULL CHECK(role IN ('student','dean')),created_at TIMESTAMPTZ DEFAULT NOW()); CREATE TABLE IF NOT EXISTS complaints(id SERIAL PRIMARY KEY,student_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,title VARCHAR(180) NOT NULL,category VARCHAR(60) NOT NULL,description TEXT NOT NULL,severity VARCHAR(20) NOT NULL,status VARCHAR(20) DEFAULT 'open',dean_response TEXT,root_cause TEXT,preventive_action TEXT,resolved_by INT REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW()); CREATE INDEX IF NOT EXISTS complaints_student_idx ON complaints(student_id);`)}
app.get('/api/session',(req,res)=>res.json({user:req.session.user||null}));
app.post('/api/register',async(req,res)=>{try{let{name,email,password,role,deanCode}=req.body;if(!name?.trim()||!email?.trim()||!password||!choice(role,['student','dean']))return res.status(400).json({error:'Complete all registration fields.'});if(password.length<8)return res.status(400).json({error:'Password must be at least 8 characters.'});email=email.trim().toLowerCase();if(role==='dean'&&deanCode!==(process.env.DEAN_ACCESS_CODE||'DEAN-2026'))return res.status(403).json({error:'Invalid dean access code.'});if((await pool.query('SELECT id FROM users WHERE email=$1',[email])).rowCount)return res.status(409).json({error:'Email already registered.'});const hash=await bcrypt.hash(password,12);const r=await pool.query('INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,$4) RETURNING id,name,email,role',[name.trim(),email,hash,role]);req.session.user=userOut(r.rows[0]);res.status(201).json({user:req.session.user})}catch(e){console.error(e);res.status(500).json({error:'Registration failed.'})}});
app.post('/api/login',async(req,res)=>{try{const{email,password,role}=req.body;const r=await pool.query('SELECT * FROM users WHERE email=$1',[email?.trim().toLowerCase()]);const u=r.rows[0];if(!u||u.role!==role||!(await bcrypt.compare(password||'',u.password_hash)))return res.status(401).json({error:'Invalid login details.'});req.session.user=userOut(u);res.json({user:req.session.user})}catch(e){console.error(e);res.status(500).json({error:'Login failed.'})}});
app.post('/api/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get('/api/complaints',auth,async(req,res)=>{try{const r=req.session.user.role==='student'?await pool.query('SELECT c.*,u.name student_name,u.email student_email FROM complaints c JOIN users u ON u.id=c.student_id WHERE c.student_id=$1 ORDER BY c.created_at DESC',[req.session.user.id]):await pool.query(`SELECT c.*,u.name student_name,u.email student_email FROM complaints c JOIN users u ON u.id=c.student_id ORDER BY CASE c.severity WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 ELSE 4 END,c.created_at DESC`);res.json({complaints:r.rows})}catch(e){console.error(e);res.status(500).json({error:'Could not load complaints.'})}});
app.post('/api/complaints',auth,role('student'),async(req,res)=>{try{const{title,category,description,severity}=req.body;if(!title?.trim()||!description?.trim()||!choice(category,categories)||!choice(severity,severities))return res.status(400).json({error:'Complete all complaint fields.'});const r=await pool.query('INSERT INTO complaints(student_id,title,category,description,severity) VALUES($1,$2,$3,$4,$5) RETURNING *',[req.session.user.id,title.trim(),category,description.trim(),severity]);res.status(201).json({complaint:r.rows[0]})}catch(e){console.error(e);res.status(500).json({error:'Could not submit complaint.'})}});
app.patch('/api/complaints/:id/resolve',role('dean'),async(req,res)=>{try{const id=Number(req.params.id),{status,deanResponse,rootCause,preventiveAction}=req.body;if(!Number.isInteger(id)||!choice(status,statuses))return res.status(400).json({error:'Invalid complaint/status.'});if(status==='resolved'&&(!deanResponse?.trim()||!rootCause?.trim()||!preventiveAction?.trim()))return res.status(400).json({error:'Resolved complaints require response, root cause and preventive action.'});const r=await pool.query(`UPDATE complaints SET status=$1,dean_response=$2,root_cause=$3,preventive_action=$4,resolved_by=CASE WHEN $1='resolved' THEN $5 ELSE NULL END,updated_at=NOW() WHERE id=$6 RETURNING *`,[status,deanResponse?.trim()||null,rootCause?.trim()||null,preventiveAction?.trim()||null,req.session.user.id,id]);if(!r.rowCount)return res.status(404).json({error:'Complaint not found.'});res.json({complaint:r.rows[0]})}catch(e){console.error(e);res.status(500).json({error:'Could not update complaint.'})}});
app.get('/health',(req,res)=>res.json({ok:true,service:'college-complaint-system'})); app.get('/{*splat}',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
init().then(()=>app.listen(PORT,'0.0.0.0',()=>console.log('Running on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
